### ISSUE TITLE
Media insertion bug on multiple rich text fields on same content type

### ISSUE THREAD

**Issue by peopledrivemecrazy** [Roslovets-Inc/strapi-plugin-ckeditor5#10]
Media library insertion when there are more than one rich text field lands on the second one. Please check the video preview.

https://user-images.githubusercontent.com/3922469/109312046-90701e00-786c-11eb-9963-3bf27a6f5a66.mp4

**Comment by roslovets** [comment]
Fixed in [v1.7.0](https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5/releases/tag/v1.7.0)
