### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by adrian-ub** [Roslovets-Inc/strapi-plugin-ckeditor5#11]
Hello, how to can add Code plugin?

**Comment by roslovets** [comment]
Hi! Just install latest version.
More info in [v1.6.0 description](https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5/releases/tag/v1.6.0).

**Comment by adrian-ub** [comment]
Only Code Block is added

I tried to add Code and I have not been able to do it

**Comment by roslovets** [comment]
Check out Code button in [v1.7.0](https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5/releases/tag/v1.7.0)
