### ISSUE TITLE
Full screen doesn't show alignment balloon

### ISSUE THREAD

**Issue by CaduGomes** [Roslovets-Inc/strapi-plugin-ckeditor5#18]
Hello!

First of all, thanks a lot for the plugin!

Now let's talk about the bug.
I can't align images when using fullscreen mode, because the alignment balloon won't show up.

Alignment balloon
![image](https://user-images.githubusercontent.com/56348747/116408052-c5670580-a808-11eb-9418-b2ae5fde6af5.png)

The media library modal also won't show up.

Thanks!! 🐛

**Comment by roslovets** [comment]
Hm, seems like full-screen editor has higher z-index. I will investigate, thanks!
