### ISSUE TITLE
customize/extend ckeditor

### ISSUE THREAD

**Issue by jo-elbdev** [Roslovets-Inc/strapi-plugin-ckeditor5#2]
Hey there! First, thank you very much for this plugin. It really is a strapi gamechanger. 

Is there a way to customize or extend the CKEditor? e.g. I need to add a h4 to the editor and I dont find anything for this in the docs. Thanks in advance!

**Comment by roslovets** [comment]
Hi! thanks for appreciating :)

To extend CKEditor you need to create and setup [custom build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html) or you can fork [my build](https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg) used in this plugin and [configure](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/configuration.html) it as you want. But after it you also will need to fork this plugin.

BTW if you want I can add [h4](https://ckeditor.com/docs/ckeditor5/latest/features/headings.html) to my build and to this plugin. I think this small feature might be useful to others.

**Comment by jo-elbdev** [comment]
Thanks for your answer! I think if it'd be useful for other users, it'd be great if you could add it to your plugin!

**Comment by roslovets** [comment]
Added in [v1.3.0](https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5/releases/tag/v1.3.0). Thank you for a good idea!
