### ISSUE TITLE
Not working resize image

### ISSUE THREAD

**Issue by LuviaB** [Roslovets-Inc/strapi-plugin-ckeditor5#21]
Hi there ! 

Thank you for your work it's really usefull ! 

I just have a problem this the resizing option and align with the text : it's not work on my html. 
How can I resolve this? 

Thank you very much !

**Comment by evanmalmud** [comment]
I didnt have this issue, but an overside or screen width or something rather than just 50%, 75% would be nice as well

**Comment by evanmalmud** [comment]
Nvm i figured our you can scale it by dragging the corners

**Comment by vub** [comment]
It's work for me too. But if you use Angular for view the HTML result. You may use `sanitizer.bypassSecurityTrustHtml`
