### ISSUE TITLE
Cannot set _target="blank" on links

### ISSUE THREAD

**Issue by finex** [Roslovets-Inc/strapi-plugin-ckeditor5#22]
Hi, on the current strapi-plugin-ckeditor5 you cannot set the _target="blank" on links. Would be possible to add this option (or document how to do)? Thank you.

**Comment by albertpak** [comment]
@roslovets any timeline updates on when will this be available?

**Comment by roslovets** [comment]
Thanks! Introduced in [v1.12.0](https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg/releases/tag/v1.12.0)

**Comment by finex** [comment]
Thank you :-)
