### ISSUE TITLE
"sourceEditing" and "removeFormat" plugins?

### ISSUE THREAD

**Issue by rowild** [Roslovets-Inc/strapi-plugin-ckeditor5#25]
Hi! I was wondering if this excellent strapi plugin of the CKeditor 5 also supports the `sourceEditing` and `removeFormat`plugins? Activating them in the `config/ckeditor.js` does not work.

According to the demo given:
https://roslovets-inc.github.io/ckeditor5-build-strapi-wysiwyg/
or the config.js here:
https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg/blob/main/src/ckeditor.js
removeFormat should actually be available. Not sure what I am doing wrong...

However, what can be done to implement "sourceEditing"?
Thank you very much!

**Comment by ScottEAdams** [comment]
removeFormat works and it looks like this pr https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg/pull/20 once complete will add sourceEditing.

**Comment by roslovets** [comment]
`removeFormat` is really available. If you can't see it in latest version of plugin, please clean Strapi `.cache` and `build` folders and do rebuild. After that clean browser history.

To implement `sourceEditing` I need help with updating CKEditor to v29.0.0: https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg/issues/18

**Comment by roslovets** [comment]
"sourceEditing" and "removeFormat" are implemented in v2.1.0-rc.1
