### ISSUE TITLE
Highlight

### ISSUE THREAD

**Issue by Irian** [Roslovets-Inc/strapi-plugin-ckeditor5#26]
Hello,

I would like to use the highlight tool in the editor, but have not yet managed to add that myself. I know how to work with the config/ckeditor.js file, but not how to add the @ckeditor/ckeditor5-highlight as a dependancy.

Could you give me some guidance on how to implement this so I can make a PR for you to implement in the next release?

The documentation: https://ckeditor.com/docs/ckeditor5/latest/features/highlight.html

Kind regards,
Irian

**Comment by roslovets** [comment]
Hi,

It's pretty easy. Just note that you should create PR in another repo (CKEditor build):
https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg

First of all install your plugin. After that you need to modify only [src/ckeditor.js](https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg/blob/main/src/ckeditor.js) - configuration stored there. Just import plugin and properly add it to configuration.
Good examples:
https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg/pull/9/files
https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg/pull/2/files
https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg/pull/6/files

**Comment by Irian** [comment]
Thanks a lot! I have added highlight and mathtype: https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg/pull/17
