### ISSUE TITLE
Compatibility with Strapi 4 Beta

### ISSUE THREAD

**Issue by johnnuman** [Roslovets-Inc/strapi-plugin-ckeditor5#33]
Hi, Is it compatible with strapi 4 beta? I tried the install instructions and it did not replace the existing editor. No errors were encountered during the install either. Please suggest thanks.

**Comment by rajatdangat07** [comment]
Hey, I have created the plugin for strapi v4. Here is the [link](https://www.npmjs.com/package/@colton75/strapi-plugin-ckeditor5)

**Comment by colton75** [comment]
Hey, I have created the plugin for strapi v4. Here is the [link](https://www.npmjs.com/package/@colton75/strapi-plugin-ckeditor5)

**Comment by marco-villanueva** [comment]
> Hey, I have created the plugin for strapi v4. Here is the [link](https://www.npmjs.com/package/@colton75/strapi-plugin-ckeditor5)

Please confirm me if I'm doing something wrong, I installed your library but I don't get the formatting in the preview. eg. H1 H2 Bold

**Comment by roslovets** [comment]
> Please confirm me if I'm doing something wrong, I installed your library but I don't get the formatting in the preview. eg. H1 H2 Bold

It's true. New Strapi frontent overrides all font styles in CKEditor preview. Formatting is working actually but you can't see it in Strapi. I'm trying to resolve this issue.

**Comment by camodigital** [comment]
> 
Thank you for sharing. Waiting for your solution.

**Comment by ihmpavel** [comment]
@roslovets Check my fix for styling issues. We are using our own patched version for more than 2 weeks. Working fine.

```
.ck-editor__main {
  /* Fix line height */
  .ck-editor__editable {
    line-height: initial;
  }
  /* Revert font styling */
  div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video {
    font: revert;
  }
  /* Revert list styling */
  ul, ol {
    list-style: initial;
    margin-left: 16px;
  }
}
```
