### ISSUE TITLE
Throws error in Strapi v4

### ISSUE THREAD

**Issue by virajsoni06** [Roslovets-Inc/strapi-plugin-ckeditor5#40]
Hi, after adding the plugin and running Strapi in dev mode, I get the below errors
![image](https://user-images.githubusercontent.com/13236286/148348058-ec4c8713-9e06-441b-8eb3-911f13f90f9d.png)

Any idea how this can be fixed?

Thanks

**Comment by drazik** [comment]
Same here, as soon as I try to access the create page or update page of a type with a rich text field, the admin UI crashes.

I stopped by running strapi server, then `yarn add strapi-plugin-ckeditor5@latest` rebuilt the admin UI and run strapi in develop mode.

**Comment by prafull-qed42** [comment]
getting the same error

**Comment by philohelp** [comment]
Same here also with 4.0.3

**Comment by victor-baumann** [comment]
It works on v4.0.4 for me for a newly generated strapi project as well as an existing updated one.

**Comment by philohelp** [comment]
Great, it also works here with 4.0.4

**Comment by virajsoni06** [comment]
Yep, it is working with 4.0.4
