### ISSUE TITLE
ckeditor crash in strapi v4.03 

### ISSUE THREAD

**Issue by quincy0** [Roslovets-Inc/strapi-plugin-ckeditor5#43]
strapi: "4.0.3",
strapi-plugin-ckeditor5: "^2.0.0-rc.2",
docker image: strapi/base

TypeError: Cannot read properties of undefined (reading 'components')

**Comment by virajsoni06** [comment]
Facing the same issue

**Comment by joeyboth** [comment]
Same!

**Comment by JesperWe** [comment]
Same in 4.0.6, where weirdly it first worked, then I removed and added back, and got same crash.
Dunno if this helps since it's minified but might give a clue:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/1643015/152198311-49ef4d6d-b254-4571-93a4-61c31b995a09.png">

**Comment by philohelp** [comment]
Did you run `yarn strapi build` - or `npm run strapi build` ? Also check for deps like in https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5/issues/42#issuecomment-1031444272

**Comment by m3m3nto** [comment]
Hello all,
it seems that with version 4.1.0 the editor is working again :)

**Comment by philohelp** [comment]
First it ceased working then I deleted node-modules & yarn.lock, did yarn, yarn strapi build and yarn strapi develop. Back to business.

**Comment by roslovets** [comment]
I can confirm, that plugin v2.1.0-rc.1 works with Strapi v4.1.5
