### ISSUE TITLE
Code and Code Block

### ISSUE THREAD

**Issue by brezhitskiy42** [Roslovets-Inc/strapi-plugin-ckeditor5#8]
Hello. Can you add [Code](https://www.npmjs.com/package/@ckeditor/ckeditor5-basic-styles) and [Code Block](https://www.npmjs.com/package/@ckeditor/ckeditor5-code-block) to this plugin?

**Comment by anderson-matt** [comment]
I updated my fork https://github.com/anderson-matt/ckeditor5-build-strapi-wysiwyg to add this functionality.  I'll do a pull request and see if roslovets wants to include this in the main repo.

**Comment by roslovets** [comment]
Thanks! Good feature. I will add.

**Comment by roslovets** [comment]
Check out [v1.6.0](https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5/releases/tag/v1.6.0)!

**Comment by roslovets** [comment]
Check out Code button in [v1.7.0](https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5/releases/tag/v1.7.0)
