### ISSUE TITLE
Fullscreen Mode Feature Request

### ISSUE THREAD

**Issue by basicserge** [Roslovets-Inc/strapi-plugin-ckeditor5#9]
First of all thanks a lot for the handy plugin! After going through the Strapi tutorial to get the ckeditor work the experience with your plugin is much more enjoyable. I like the fact that the translation is already works out of the box and that the plugin already has a set of nice features, especially image uploads! Maybe one thing would enhance my own experience: if the empty config had some kind of a commented template with features that could be used there, cause initially I was not attentive enough and just copied literally everything from the reference config. But that's just me! 😎

What I would really want to have is the button to use the ckeditor in the fullscreen mode. Just like the default Strapi editor does is fine. I would add to that that while the width of the editor area is more or less comfortable, it's height is not enough IMHO working with large volume texts. Thanks again!

**Comment by roslovets** [comment]
Great ideas, thanks!

**Comment by roslovets** [comment]
Check out [v1.6.0](https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5/releases/tag/v1.6.0)!

**Comment by basicserge** [comment]
> Check out [v1.6.0](https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5/releases/tag/v1.6.0)!

Just checked. 
That's incredibly awesome! You made my day, thanks a lot! 🎈🎆🧡
